/**
 * Seed Components
 * Adds sample robotics components to the database
 */

import "dotenv/config";
import { PrismaClient } from '../generated/prisma/client.js';
import { PrismaPg } from '@prisma/adapter-pg';

const connectionString = `${process.env.DATABASE_URL}`;
const adapter = new PrismaPg({ connectionString });
const prisma = new PrismaClient({ adapter });

const sampleComponents = [
  {
    name: 'Arduino Uno R3',
    sku: 'ARD-UNO-R3',
    description: 'Microcontroller board based on the ATmega328P. Features 14 digital I/O pins, 6 analog inputs, a 16 MHz crystal oscillator, USB connection, power jack, ICSP header, and reset button.',
    typicalUseCase: 'General purpose microcontroller for robotics projects, automation, and IoT applications',
    vendorLink: 'https://store.arduino.cc/products/arduino-uno-rev3',
    imageUrl: 'https://cdn.pixabay.com/photo/2017/03/23/12/32/arduino-2168193_1280.png',
    unitPriceCents: 119900, // ₹1,199
    stockQuantity: 50,
    isActive: true,
  },
  {
    name: 'Raspberry Pi 4 Model B (4GB)',
    sku: 'RPI4-4GB',
    description: '1.5GHz quad-core ARM Cortex-A72 CPU, 4GB LPDDR4 RAM, dual-band WiFi, Bluetooth 5.0, Gigabit Ethernet, 2x USB 3.0, 2x USB 2.0, dual 4K display support.',
    typicalUseCase: 'Robot brain, computer vision, machine learning, home automation, media center',
    vendorLink: 'https://www.raspberrypi.com/products/raspberry-pi-4-model-b/',
    imageUrl: 'https://cdn.pixabay.com/photo/2017/03/23/12/32/arduino-2168193_1280.png',
    unitPriceCents: 549900, // ₹5,499
    stockQuantity: 30,
    isActive: true,
  },
  {
    name: 'HC-SR04 Ultrasonic Sensor',
    sku: 'SENS-HC-SR04',
    description: 'Ultrasonic distance sensor module. Range: 2cm-400cm, accuracy ±3mm. Operating voltage 5V DC.',
    typicalUseCase: 'Obstacle detection, distance measurement, proximity sensing in mobile robots',
    vendorLink: null,
    imageUrl: 'https://cdn.pixabay.com/photo/2017/03/23/12/32/arduino-2168193_1280.png',
    unitPriceCents: 9900, // ₹99
    stockQuantity: 200,
    isActive: true,
  },
  {
    name: 'L298N Motor Driver',
    sku: 'MOT-L298N',
    description: 'Dual H-Bridge motor driver module. Controls 2 DC motors or 1 stepper motor. Max current 2A per channel. Input voltage 5-35V.',
    typicalUseCase: 'Drive DC motors and stepper motors in mobile robots, robotic arms',
    vendorLink: null,
    imageUrl: 'https://cdn.pixabay.com/photo/2017/03/23/12/32/arduino-2168193_1280.png',
    unitPriceCents: 14900, // ₹149
    stockQuantity: 75,
    isActive: true,
  },
  {
    name: 'SG90 Micro Servo Motor',
    sku: 'SERVO-SG90',
    description: 'Lightweight servo motor. Operating voltage 4.8-6V, torque 1.8kg/cm, speed 0.1s/60°. 180° rotation.',
    typicalUseCase: 'Camera gimbals, robotic arms, gripper mechanisms, pan-tilt systems',
    vendorLink: null,
    imageUrl: 'https://cdn.pixabay.com/photo/2017/03/23/12/32/arduino-2168193_1280.png',
    unitPriceCents: 12900, // ₹129
    stockQuantity: 150,
    isActive: true,
  },
  {
    name: 'MPU6050 Gyroscope + Accelerometer',
    sku: 'SENS-MPU6050',
    description: '6-axis motion tracking device. 3-axis gyroscope, 3-axis accelerometer. I2C interface. Range: ±2g to ±16g, ±250°/s to ±2000°/s.',
    typicalUseCase: 'Balance detection in self-balancing robots, drones, motion tracking',
    vendorLink: null,
    imageUrl: 'https://cdn.pixabay.com/photo/2017/03/23/12/32/arduino-2168193_1280.png',
    unitPriceCents: 19900, // ₹199
    stockQuantity: 100,
    isActive: true,
  },
  {
    name: 'ESP32 DevKit V1',
    sku: 'ESP32-DEVKIT',
    description: 'WiFi + Bluetooth microcontroller. Dual-core 240MHz, 520KB SRAM, 4MB Flash. 30 GPIO pins, ADC, DAC, PWM, I2C, SPI, UART.',
    typicalUseCase: 'IoT robots, wireless control, WiFi-enabled projects, web servers',
    vendorLink: 'https://www.espressif.com/en/products/devkits',
    imageUrl: 'https://cdn.pixabay.com/photo/2017/03/23/12/32/arduino-2168193_1280.png',
    unitPriceCents: 39900, // ₹399
    stockQuantity: 60,
    isActive: true,
  },
  {
    name: '12V DC Geared Motor (300 RPM)',
    sku: 'MOT-12V-300RPM',
    description: 'High torque DC geared motor. 12V, 300 RPM, 10kg-cm torque. 6mm shaft diameter. Metal gearbox.',
    typicalUseCase: 'Wheeled robots, conveyor systems, heavy-duty applications',
    vendorLink: null,
    imageUrl: 'https://cdn.pixabay.com/photo/2017/03/23/12/32/arduino-2168193_1280.png',
    unitPriceCents: 29900, // ₹299
    stockQuantity: 40,
    isActive: true,
  },
  {
    name: 'Breadboard 830 Points',
    sku: 'BREAD-830',
    description: 'Solderless breadboard with 830 tie points. Size: 165x55mm. 2x power rails, 630 connection points.',
    typicalUseCase: 'Prototyping circuits, testing components, learning electronics',
    vendorLink: null,
    imageUrl: 'https://cdn.pixabay.com/photo/2017/03/23/12/32/arduino-2168193_1280.png',
    unitPriceCents: 7900, // ₹79
    stockQuantity: 120,
    isActive: true,
  },
  {
    name: 'Jumper Wire Set (65 pieces)',
    sku: 'WIRE-JUMP-65',
    description: 'Male-to-Male jumper wires. 65 pieces, multiple colors, 20cm length. Compatible with breadboards.',
    typicalUseCase: 'Circuit connections, breadboard projects, prototyping',
    vendorLink: null,
    imageUrl: 'https://cdn.pixabay.com/photo/2017/03/23/12/32/arduino-2168193_1280.png',
    unitPriceCents: 4900, // ₹49
    stockQuantity: 250,
    isActive: true,
  },
  {
    name: 'Li-Po Battery 3.7V 2000mAh',
    sku: 'BAT-LIPO-2000',
    description: 'Rechargeable Lithium Polymer battery. 3.7V nominal, 2000mAh capacity. JST connector. Dimensions: 60x34x10mm.',
    typicalUseCase: 'Power source for mobile robots, drones, portable projects',
    vendorLink: null,
    imageUrl: 'https://cdn.pixabay.com/photo/2017/03/23/12/32/arduino-2168193_1280.png',
    unitPriceCents: 34900, // ₹349
    stockQuantity: 45,
    isActive: true,
  },
  {
    name: 'NEMA 17 Stepper Motor',
    sku: 'STEP-NEMA17',
    description: 'Bipolar stepper motor. 1.8° step angle (200 steps/rev), 1.2A rated current, 0.28Nm holding torque. 42x42x39mm.',
    typicalUseCase: '3D printers, CNC machines, robotic arms, precise positioning systems',
    vendorLink: null,
    imageUrl: 'https://cdn.pixabay.com/photo/2017/03/23/12/32/arduino-2168193_1280.png',
    unitPriceCents: 59900, // ₹599
    stockQuantity: 25,
    isActive: true,
  },
];

const catalogProducts = [
  {
    name: 'Arduino Uno R3',
    sku: 'ARD-UNO-R3',
    category: 'Development Boards',
    subcategory: 'Arduino Boards',
    productType: 'DEVELOPMENT_BOARD',
    brand: 'Arduino',
    tags: ['microcontroller', 'arduino', 'student-projects'],
    isBestSeller: true,
  },
  {
    name: 'ESP32 DevKit V1',
    sku: 'ESP32-DEVKIT',
    category: 'Development Boards',
    subcategory: 'WiFi & Bluetooth Boards',
    productType: 'DEVELOPMENT_BOARD',
    brand: 'Espressif',
    tags: ['iot', 'wifi', 'bluetooth'],
    isBestSeller: true,
  },
  {
    name: 'Raspberry Pi 4 Model B (4GB)',
    sku: 'RPI4-4GB',
    category: 'Development Boards',
    subcategory: 'Single Board Computers',
    productType: 'DEVELOPMENT_BOARD',
    brand: 'Raspberry Pi',
    tags: ['linux', 'computer-vision', 'ai'],
  },
  {
    name: 'HC-SR04 Ultrasonic Sensor',
    sku: 'SENS-HC-SR04',
    category: 'Sensors',
    subcategory: 'Distance Sensors',
    productType: 'SENSOR',
    tags: ['robotics', 'obstacle-detection'],
    isBestSeller: true,
  },
  {
    name: 'MPU6050 Gyroscope + Accelerometer',
    sku: 'SENS-MPU6050',
    category: 'Sensors',
    subcategory: 'Motion Sensors',
    productType: 'SENSOR',
    tags: ['imu', 'drone', 'self-balancing'],
  },
  {
    name: 'L298N Motor Driver',
    sku: 'MOT-L298N',
    category: 'Semiconductors',
    subcategory: 'Motor Driver ICs & Modules',
    productType: 'MODULE',
    tags: ['motor-driver', 'robot-car'],
    isBestSeller: true,
  },
  {
    name: 'SG90 Micro Servo Motor',
    sku: 'SERVO-SG90',
    category: 'Motors & Actuators',
    subcategory: 'Servo Motors',
    productType: 'MOTOR_ACTUATOR',
    tags: ['servo', 'robotic-arm', 'aero-modeling'],
    isBestSeller: true,
  },
  {
    name: '12V DC Geared Motor (300 RPM)',
    sku: 'MOT-12V-300RPM',
    category: 'Motors & Actuators',
    subcategory: 'DC Geared Motors',
    productType: 'MOTOR_ACTUATOR',
    tags: ['dc-motor', 'robotics'],
  },
  {
    name: 'NEMA 17 Stepper Motor',
    sku: 'STEP-NEMA17',
    category: 'Motors & Actuators',
    subcategory: 'Stepper Motors',
    productType: 'MOTOR_ACTUATOR',
    tags: ['stepper', 'cnc', '3d-printer'],
  },
  {
    name: 'Li-Po Battery 3.7V 2000mAh',
    sku: 'BAT-LIPO-2000',
    category: 'Power & Batteries',
    subcategory: 'Li-Po Batteries',
    productType: 'POWER_BATTERY',
    tags: ['battery', 'drone', 'portable'],
  },
  {
    name: 'Breadboard 830 Points',
    sku: 'BREAD-830',
    category: 'Tools & Prototyping',
    subcategory: 'Breadboards',
    productType: 'TOOL_EQUIPMENT',
    tags: ['prototyping', 'lab'],
  },
  {
    name: 'Jumper Wire Set (65 pieces)',
    sku: 'WIRE-JUMP-65',
    category: 'Tools & Prototyping',
    subcategory: 'Wires & Connectors',
    productType: 'TOOL_EQUIPMENT',
    tags: ['wires', 'breadboard'],
  },
  {
    name: 'DHT22 Temperature & Humidity Sensor',
    sku: 'SENS-DHT22',
    description: 'Digital temperature and humidity sensor for weather stations and IoT monitoring.',
    typicalUseCase: 'Weather station, agriculture monitoring, smart home climate sensing',
    imageUrl: 'https://cdn.pixabay.com/photo/2017/03/23/12/32/arduino-2168193_1280.png',
    unitPriceCents: 24900,
    stockQuantity: 90,
    isActive: true,
    category: 'Sensors',
    subcategory: 'Environment Sensors',
    productType: 'SENSOR',
    tags: ['temperature', 'humidity', 'iot'],
  },
  {
    name: '1/4W Resistor Assortment Kit',
    sku: 'PASS-RES-KIT-600',
    description: 'Assorted through-hole resistors for breadboard and PCB electronics work.',
    typicalUseCase: 'Basic electronics, prototyping, student labs, repair work',
    imageUrl: 'https://cdn.pixabay.com/photo/2017/03/23/12/32/arduino-2168193_1280.png',
    unitPriceCents: 19900,
    stockQuantity: 150,
    isActive: true,
    category: 'Passive Components',
    subcategory: 'Resistors',
    productType: 'ELECTRONICS_COMPONENT',
    tags: ['resistor', 'passive', 'starter-kit'],
  },
  {
    name: 'Electrolytic Capacitor Assortment Kit',
    sku: 'PASS-CAP-ELEC-KIT',
    description: 'Common electrolytic capacitor values for power filtering and general circuits.',
    typicalUseCase: 'Power supplies, filtering, repair, electronics labs',
    imageUrl: 'https://cdn.pixabay.com/photo/2017/03/23/12/32/arduino-2168193_1280.png',
    unitPriceCents: 24900,
    stockQuantity: 120,
    isActive: true,
    category: 'Passive Components',
    subcategory: 'Capacitors',
    productType: 'ELECTRONICS_COMPONENT',
    tags: ['capacitor', 'passive', 'power'],
  },
  {
    name: '5mm LED Assortment Pack',
    sku: 'PASS-LED-5MM-MIX',
    description: 'Mixed color 5mm LEDs for indicators, displays, and beginner circuits.',
    typicalUseCase: 'Indicators, breadboard learning, display experiments',
    imageUrl: 'https://cdn.pixabay.com/photo/2017/03/23/12/32/arduino-2168193_1280.png',
    unitPriceCents: 9900,
    stockQuantity: 250,
    isActive: true,
    category: 'Passive Components',
    subcategory: 'LEDs',
    productType: 'ELECTRONICS_COMPONENT',
    tags: ['led', 'indicator'],
  },
  {
    name: '16x2 LCD Display Module',
    sku: 'DISP-LCD-16X2',
    description: 'Character LCD display for Arduino, IoT, and embedded projects.',
    typicalUseCase: 'Project UI, sensor displays, menu systems',
    imageUrl: 'https://cdn.pixabay.com/photo/2017/03/23/12/32/arduino-2168193_1280.png',
    unitPriceCents: 17900,
    stockQuantity: 80,
    isActive: true,
    category: 'Displays',
    subcategory: 'LCD Displays',
    productType: 'MODULE',
    tags: ['lcd', 'display', 'arduino'],
  },
  {
    name: '0.96 inch OLED Display I2C',
    sku: 'DISP-OLED-096-I2C',
    description: 'Compact OLED display module with I2C interface.',
    typicalUseCase: 'Wearables, IoT status screens, compact dashboards',
    imageUrl: 'https://cdn.pixabay.com/photo/2017/03/23/12/32/arduino-2168193_1280.png',
    unitPriceCents: 29900,
    stockQuantity: 65,
    isActive: true,
    category: 'Displays',
    subcategory: 'OLED Displays',
    productType: 'MODULE',
    tags: ['oled', 'display', 'i2c'],
  },
  {
    name: 'HC-05 Bluetooth Module',
    sku: 'COMM-HC05-BT',
    description: 'Bluetooth serial module for wireless microcontroller communication.',
    typicalUseCase: 'Phone-controlled robots, wireless serial links, Bluetooth projects',
    imageUrl: 'https://cdn.pixabay.com/photo/2017/03/23/12/32/arduino-2168193_1280.png',
    unitPriceCents: 34900,
    stockQuantity: 70,
    isActive: true,
    category: 'Communication Modules',
    subcategory: 'Bluetooth Modules',
    productType: 'MODULE',
    tags: ['bluetooth', 'wireless', 'serial'],
  },
  {
    name: 'LoRa SX1278 Wireless Module',
    sku: 'COMM-LORA-SX1278',
    description: 'Long range LoRa wireless communication module for IoT projects.',
    typicalUseCase: 'Long range IoT, agriculture monitoring, remote telemetry',
    imageUrl: 'https://cdn.pixabay.com/photo/2017/03/23/12/32/arduino-2168193_1280.png',
    unitPriceCents: 69900,
    stockQuantity: 35,
    isActive: true,
    category: 'Communication Modules',
    subcategory: 'LoRa Modules',
    productType: 'MODULE',
    tags: ['lora', 'iot', 'wireless'],
  },
  {
    name: 'JST Connector Kit',
    sku: 'CONN-JST-KIT',
    description: 'Assorted JST connectors and leads for batteries, sensors, and compact electronics.',
    typicalUseCase: 'Battery wiring, sensor harnesses, product prototypes',
    imageUrl: 'https://cdn.pixabay.com/photo/2017/03/23/12/32/arduino-2168193_1280.png',
    unitPriceCents: 19900,
    stockQuantity: 100,
    isActive: true,
    category: 'Connectors & Cables',
    subcategory: 'Connectors',
    productType: 'ELECTRONICS_COMPONENT',
    tags: ['connector', 'jst', 'cable'],
  },
  {
    name: 'Custom PCB Design & Manufacturing Service',
    sku: 'SERV-PCB-MFG',
    description: 'Custom PCB design review and manufacturing support for prototypes and products.',
    typicalUseCase: 'Student PCBs, product prototypes, institution lab boards',
    imageUrl: 'https://cdn.pixabay.com/photo/2017/03/23/12/32/arduino-2168193_1280.png',
    unitPriceCents: 299900,
    stockQuantity: 999,
    isActive: true,
    category: 'PCB & Manufacturing',
    subcategory: 'PCB Services',
    productType: 'CUSTOM_PROJECT_SERVICE',
    tags: ['pcb', 'manufacturing', 'custom-service'],
  },
  {
    name: 'Digital Multimeter',
    sku: 'TOOL-DMM-BASIC',
    description: 'Digital multimeter for voltage, current, continuity, and resistance measurements.',
    typicalUseCase: 'Electronics labs, debugging, repair, student projects',
    imageUrl: 'https://cdn.pixabay.com/photo/2017/03/23/12/32/arduino-2168193_1280.png',
    unitPriceCents: 59900,
    stockQuantity: 30,
    isActive: true,
    category: 'Test & Measurement',
    subcategory: 'Multimeters',
    productType: 'TOOL_EQUIPMENT',
    tags: ['multimeter', 'testing', 'lab'],
  },
  {
    name: '4S 30A BMS Module',
    sku: 'PWR-BMS-4S-30A',
    description: 'Battery management system for 4S lithium battery packs.',
    typicalUseCase: 'Custom battery packs, robotics power systems, e-bike prototypes',
    imageUrl: 'https://cdn.pixabay.com/photo/2017/03/23/12/32/arduino-2168193_1280.png',
    unitPriceCents: 39900,
    stockQuantity: 40,
    isActive: true,
    category: 'Power & Batteries',
    subcategory: 'BMS & Chargers',
    productType: 'POWER_BATTERY',
    tags: ['bms', 'battery-pack'],
  },
  {
    name: 'Drone Flight Controller F4',
    sku: 'DRONE-FC-F4',
    description: 'F4 flight controller board for quadcopter and UAV builds.',
    typicalUseCase: 'Drones, UAV prototypes, student aerospace projects',
    imageUrl: 'https://cdn.pixabay.com/photo/2017/03/23/12/32/arduino-2168193_1280.png',
    unitPriceCents: 249900,
    stockQuantity: 18,
    isActive: true,
    category: 'Drones & Aerospace',
    subcategory: 'Flight Controllers',
    productType: 'MODULE',
    tags: ['drone', 'uav', 'flight-controller'],
  },
  {
    name: 'Aero Modeling Plane Electronics Kit',
    sku: 'AERO-PLANE-ELEC-KIT',
    description: 'Electronics pack for aero modeling plane builds with servo, control, and power accessories.',
    typicalUseCase: 'Aero modeling planes, RC plane student projects',
    imageUrl: 'https://cdn.pixabay.com/photo/2017/03/23/12/32/arduino-2168193_1280.png',
    unitPriceCents: 399900,
    stockQuantity: 12,
    isActive: true,
    category: 'Drones & Aerospace',
    subcategory: 'Aero Modeling Kits',
    productType: 'COURSE_KIT',
    tags: ['aero-modeling', 'rc-plane'],
  },
  {
    name: 'Robomaniac Lego Robotics Course Kit',
    sku: 'RM-LEGO-ROBOTICS-KIT',
    description: 'Robomaniac course kit for Lego-based robotics learning programs.',
    typicalUseCase: 'School robotics courses, institution labs, beginner robotics education',
    imageUrl: 'https://cdn.pixabay.com/photo/2017/03/23/12/32/arduino-2168193_1280.png',
    unitPriceCents: 849900,
    stockQuantity: 20,
    isActive: true,
    category: 'Robomaniac Store',
    subcategory: 'Lego Robotics Course Kits',
    productType: 'COURSE_KIT',
    brand: 'Robomaniac',
    tags: ['robomaniac', 'lego', 'course-kit'],
    isBestSeller: true,
    isRobomaniacItem: true,
  },
  {
    name: 'Robomaniac Robotics Course Kit',
    sku: 'RM-ROBOTICS-COURSE-KIT',
    description: 'Hands-on robotics course kit for schools, colleges, and training centers.',
    typicalUseCase: 'Robotics classroom programs, workshops, student learning kits',
    imageUrl: 'https://cdn.pixabay.com/photo/2017/03/23/12/32/arduino-2168193_1280.png',
    unitPriceCents: 699900,
    stockQuantity: 35,
    isActive: true,
    category: 'Robomaniac Store',
    subcategory: 'Robotics Course Kits',
    productType: 'COURSE_KIT',
    brand: 'Robomaniac',
    tags: ['robomaniac', 'robotics', 'course-kit'],
    isBestSeller: true,
    isRobomaniacItem: true,
  },
  {
    name: 'Robomaniac Robotics & AI Book',
    sku: 'RM-ROBOTICS-AI-BOOK',
    description: 'Robotics and AI learning book from Robomaniac for guided student learning.',
    typicalUseCase: 'Robotics curriculum, AI basics, classroom learning',
    imageUrl: 'https://cdn.pixabay.com/photo/2017/03/23/12/32/arduino-2168193_1280.png',
    unitPriceCents: 99900,
    stockQuantity: 100,
    isActive: true,
    category: 'Robomaniac Store',
    subcategory: 'Books',
    productType: 'BOOK',
    brand: 'Robomaniac',
    tags: ['book', 'robotics', 'ai'],
    isRobomaniacItem: true,
  },
  {
    name: 'BlockSquare Software',
    sku: 'RM-BLOCKSQUARE-SOFTWARE',
    description: 'Robomaniac BlockSquare visual programming software for learning logic, robotics, and automation.',
    typicalUseCase: 'Block-based coding, robotics classrooms, beginner programming',
    imageUrl: 'https://cdn.pixabay.com/photo/2017/03/23/12/32/arduino-2168193_1280.png',
    unitPriceCents: 199900,
    stockQuantity: 999,
    isActive: true,
    category: 'Robomaniac Store',
    subcategory: 'Software',
    productType: 'SOFTWARE',
    brand: 'Robomaniac',
    tags: ['blocksquare', 'software', 'visual-programming'],
    isRobomaniacItem: true,
    isSoftware: true,
  },
];

async function seedComponents() {
  console.log('🌱 Seeding components...');

  try {
    const productsBySku = new Map<string, any>();

    for (const component of sampleComponents) {
      if (component.sku) productsBySku.set(component.sku, component);
    }

    for (const product of catalogProducts) {
      if (product.sku) {
        productsBySku.set(product.sku, {
          ...(productsBySku.get(product.sku) || {}),
          ...product,
        });
      }
    }

    for (const product of productsBySku.values()) {
      await prisma.component.upsert({
        where: { sku: product.sku },
        update: product,
        create: product,
      });
      console.log(`✅ Upserted ${product.name}`);
    }

    console.log('\n✨ Component seeding complete!');
  } catch (error) {
    console.error('❌ Error seeding components:', error);
    throw error;
  } finally {
    await prisma.$disconnect();
  }
}

seedComponents();
